### ISSUE TITLE
Problem with database schema to import

### ISSUE THREAD

**Issue by Sarbaz634** [ManyDesigns/Portofino#456]
Hello,

I`m facing the problem with importing database schema objects. It`s appears on the second step when running Wizard.

I found following error messages  in catalina.out file:

"ERROR c.m.p.p.hibernate.SessionFactoryBuilder  admin /api/portofino-upstairs/database/connections/MY_DB_NAME/schemas
 The foreign key MY_DB_NAME.TEST_USER.TABLE_2$FK_ID does not refer to the exact primary key of table MY_DB_NAME.TEST_USER.TABLE_1, this is not supported."

I`ve checked it from database side and found out that foreign key has defined to reference the column of a UNIQUE constraint in table1.
So, as far as i know FOREIGN KEY constraint does not have to be linked only to a PRIMARY KEY constraint in another table. It can be also defined to reference the columns of a UNIQUE constraint in another table.

So, need solution to fix the problem. 

Thanks.

**Comment by alessiostalla** [comment]
At the moment, this is not supported. However, this doesn't prevent the table to be mapped; it only means that the foreign key won't be mapped. You can get around some uses of the foreign key with a selection provider. If that is not sufficient – because, e.g., you want to have a mapped property that you can navigate in Groovy code or HQL queries – you can always map the table manually with a Java class with JPA/Hibernate annotations, however that's not well-documented and the class must have some non-obvious requirements, so it's really a last resort.

**Comment by Sarbaz634** [comment]
Okay. Can you pls clarify, how was  the users  registration  configured in portofino 5.2.1?
thanks

**Comment by alessiostalla** [comment]
You should write to the mailing list for such inquiries.
