### ISSUE TITLE
PortofinoSupport + Dispatcher

### ISSUE THREAD

**Issue by alessiostalla** [ManyDesigns/Portofino#594]

**Comment by alessiostalla** [comment]
@iacopo-filiberto I think I made it work, see https://github.com/ManyDesigns/Portofino/blob/f1d311adb093ea1f03792485d334ad7a34848cda/microservices/spring-boot/src/test/java/com/manydesigns/portofino/microservices/boot/PortofinoBootSupportTest.java 
Could you try it before we release it, by building Portofino 5.3.4-SNAPSHOT from source?

**Comment by iacopo-filiberto** [comment]
Hi @alessiostalla i'll try tomorrow with the test project that i have locally.

**Comment by alessiostalla** [comment]
Great! Please note two things in the test I've linked:

1. portofino.dispatcher.enabled=true property (in application.properties for example)
2. Explicitly importing ElementsAutoConfiguration.class, PortofinoDispatcherSupport.class, and PortofinoJerseyAutoConfiguration.class. I'm not sure that's necessary in a Boot application but the test wasn't picking them up for some reason.

Also, I struggled a bit to find the right dependencies to include because otherwise pieces of Jersey are missing. Hopefully just depending on portofino-spring-boot works but in case it doesn't look at the test dependencies I've added to portofino-spring-boot.

**Comment by iacopo-filiberto** [comment]
Ok @alessiostalla  i tried on my local project and it's working fine with a custom actions, but i have some errors when i try to use a crud action; 
the main problems that i've found so far are:
1. Portofino looks for the configuration.xml in the wrong path:
   `target/classes/com/manydesigns/portofino/resourceaction/cars/CarsAction.class/configuration.xml` should be `target/classes/com/manydesigns/portofino/resourceaction/cars/configuration.xml` because the fragment that I registered my action is `cars`
2. Crud actions depends on the BlobManager and CrudExporterRegistry, at the moment i've defined the beans in the app but we need to define this beans in a module... maybe ResourceActionsModule?

If you want i can put my local test project on git so it is possible to reproduce the errors.

**Comment by alessiostalla** [comment]
OK so regarding 1. I think you're doing something strange and I'd like to see your code. Because normally actions should go in `target/classes/portofino/actions` (that is, `src/main/resources/portofino/actions` in the source).

Regarding 2. I've published the BlobManager as a bean now in `PortofinoSupport.class`, while to get the CrudExporterRegistry you have to import `CrudModule.class`. You can see this in [the updated test](https://github.com/ManyDesigns/Portofino/blob/b1888f34926b81472259af32a52ea122a924e9fc/microservices/spring-boot/src/test/java/com/manydesigns/portofino/microservices/boot/PortofinoBootSupportTest.java) which now ensures that we can invoke a CRUD action.

Also worth noting is that this doesn't support Groovy at the moment, only Java.

**Comment by iacopo-filiberto** [comment]
Hi @alessiostalla, sorry for the delay in the answer;

Regarding 1 i've resolved the issue: i was declaring the actions in the wrong package, now it's working fine.
Regarding 2 it's seems to be all fine.

I've created a repo with my code if you want to have a look at what i've done; it's available [here](https://github.com/iacopo-filiberto/test-portofino-spring-module)

**Comment by alessiostalla** [comment]
Hi @iacopo-filiberto cool thanks I'm happy it's working fine. Your code looks good.

Do you think we can improve on this? E.g. we could make the actions base directory configurable.
