### ISSUE TITLE
Portofino + SSL

### ISSUE THREAD

**Issue by G1mpy** [ManyDesigns/Portofino#602]
I was able to setup Portofino out of the can with no problems.

When searching for setting up for SSL, I didn't find anything except some general posts about setting up SSL for Tomcat. In server.xml I did comment out the port 8080 part. And uncomment and try each of the commented 8443 parts. But I always get "connection refused". 

I am running this on a jailed SSH from my hosting provider. The provided PHP related https://  URLs work fine.

Any suggestions on what needs to be done to get SSL working?

**Comment by alessiostalla** [comment]
Hello. There's nothing specific to Portofino regarding setting up SSL.

If your provider includes PHP and it's working under HTTPS, it means that there's already a web server installed (e.g. Apache httpd or Nginx). So, enabling HTTPS on Tomcat is unnecessary because Tomcat will stay behind the web-facing HTTP(S) server. In fact, port 8443 is most probably not open to the Internet and that's why you get a connection refused error when trying to connect to it. 

You should instead focus on hooking the installed web server with Tomcat. The web server would then act as a "reverse proxy" that handles HTTPS for you. You should easily find documentation on how to do that.
